name: kratos_plugin
description: Runtime support for kratos dart http client.
version: 0.0.1
repository: https://github.com/kvii/kratos-plugin.git

environment:
  sdk: ^3.1.0

dependencies:
  json_annotation: ^4.8.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
